In [1]:
import pandas as pd
import numpy as np

## EPH survey data

In [332]:
df = pd.read_csv('./../resumen_EPH_hogar.csv')
df = df.loc[df.IV1 != 9]
df['IV10'] = df['IV10'].map({1: 1, 2: 2, 3: 2, 0: 0, 9: 9})
df['II9'] = df['II9'].map({1: 1, 2: 2, 3: 2, 4: 4, 0: 0})
df['II7'] = df['II7'].map({1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 6, 8: 6, 9: 6, 0: 0})
df['IX_TOT'] = df['IX_TOT'].clip(0, 8)


In [4]:
# df.groupby(['AGLOMERADO']).nunique()

In [3]:
# for col in df.iloc[:, 2:].columns:
#     print col
#     print sorted(df[col].unique())

## 2010 ARG Census data

In [5]:
path = './../../Datos_censo/Preguntas/'

VIVIENDA_V01 = pd.read_csv(path + 'VIVIENDA-V01.csv', encoding = 'latin-1')
HOGAR_H05 = pd.read_csv(path + 'HOGAR-H05.csv', encoding = 'latin-1') # Pisos
HOGAR_H06 = pd.read_csv(path + 'HOGAR-H06.csv', encoding = 'latin-1') # Cubierta techos
HOGAR_H07 = pd.read_csv(path + 'HOGAR-H07.csv', encoding = 'latin-1') # Cielorraso
HOGAR_H08 = pd.read_csv(path + 'HOGAR-H08.csv', encoding = 'latin-1') # Agua
HOGAR_H09 = pd.read_csv(path + 'HOGAR-H09.csv', encoding = 'latin-1') # Procedencia agua
HOGAR_H10 = pd.read_csv(path + 'HOGAR-H10.csv', encoding = 'latin-1') # Tiene baño
HOGAR_H11 = pd.read_csv(path + 'HOGAR-H11.csv', encoding = 'latin-1') # Baño con cadena
HOGAR_H12 = pd.read_csv(path + 'HOGAR-H12.csv', encoding = 'latin-1') # Desague baño
HOGAR_H13 = pd.read_csv(path + 'HOGAR-H13.csv', encoding = 'latin-1') # Baño uso exclusivo
HOGAR_H14 = pd.read_csv(path + 'HOGAR-H14.csv', encoding = 'latin-1') # Combustible cocina
HOGAR_PROP = pd.read_csv(path + 'HOGAR-PROP.csv', encoding = 'latin-1') # Regimen tenencia
HOGAR_TOTPERS = pd.read_csv(path + 'HOGAR-TOTPERS.csv', encoding = 'latin-1') # Personas en hogar

df_list = [VIVIENDA_V01, HOGAR_H05, HOGAR_H06, HOGAR_H07, HOGAR_H08, HOGAR_H09, 
          HOGAR_H10, HOGAR_H11, HOGAR_H12, HOGAR_H13, HOGAR_H14, HOGAR_PROP, HOGAR_TOTPERS]

## Harmonise variables (let valid answers match exactly in both datasets)

In [217]:

VIVIENDA_V01['2 Departamento'] = VIVIENDA_V01['4 Departamento']
VIVIENDA_V01['3 Pieza de inquilinato'] = VIVIENDA_V01['5 Pieza en inquilinato']
VIVIENDA_V01[u'4 Pieza en hotel / pensión'] = VIVIENDA_V01[u'6 Pieza en hotel familiar o pensión']
VIVIENDA_V01[u'5 Local no construido para habitación'] = VIVIENDA_V01[u'7 Local no construido para habitación']
VIVIENDA_V01['6 Otros'] = VIVIENDA_V01['2 Rancho'] + VIVIENDA_V01['3 Casilla'] + VIVIENDA_V01[u'8 Vivienda móvil'] + VIVIENDA_V01['9 Persona/s viviendo en la calle']

IV1_censo = VIVIENDA_V01[['radio', '1 Casa', '2 Departamento', '3 Pieza de inquilinato', u'4 Pieza en hotel / pensión',
                         u'5 Local no construido para habitación', '6 Otros', 'TOTAL']]
IV3_censo = HOGAR_H05
IV3_censo.columns = ['radio', '1 Mosaico / baldosa / madera / cerámica / alfombra', 
                    '2 Cemento / ladrillo fijo', '3 Ladrillo suelto / tierra', '4 Otro', 'TOTAL']

IV4_censo = HOGAR_H06
IV4_censo.columns = ['radio', '1 Membrana / cubierta asfáltica', '2 Baldosa / losa sin cubierta', '3 Pizarra / teja', 
                     '4 Chapa de metal sin cubierta', '5 Chapa de fibrocemento / plástico', '6 Chapa de cartón', 
                     '7 Caña / tabla / paja con barro / paja sola', '9 N/S. Depto en propiedad horizontal', 'TOTAL']

IV5_censo = HOGAR_H07
IV6_censo = HOGAR_H08
IV7_censo = HOGAR_H09
IV7_censo['4 Otra fuente'] = HOGAR_H09['4 Pozo'] + HOGAR_H09['5 Transporte por cisterna'] + \
 HOGAR_H09[u'6 Agua de lluvia, río, canal, arroyo o acequia']
IV7_censo = IV7_censo[[u'radio', u'1 Red pública', u'2 Perforación con bomba a motor',
                      u'3 Perforación con bomba manual', u'4 Otra fuente', u'TOTAL']]

IV8_censo = HOGAR_H10
IV10_censo = HOGAR_H11
IV11_censo = HOGAR_H12
II9_censo = HOGAR_H13

II8_censo = HOGAR_H14
II8_censo['2 Gas de tubo / garrafa'] = HOGAR_H14['3 Gas en tubo'] + HOGAR_H14['4 Gas en garrafa']
II8_censo[u'3 Kerosene / leña/ carbón'] = HOGAR_H14[u'6 Leña o carbón']
II8_censo['4 Otro'] = HOGAR_H14[u'2 Gas a granel (zeppelin)'] + HOGAR_H14[u'5 Electricidad'] + HOGAR_H14[u'7 Otro']

II8_censo = II8_censo[['radio', '1 Gas de red', '2 Gas de tubo / garrafa', u'3 Kerosene / leña/ carbón', '4 Otro', 'TOTAL']]

II7_censo = HOGAR_PROP

IX_TOT_censo = HOGAR_TOTPERS

## Intento Max Ent

#### Margins

In [213]:
# From whole country data, we can only have margins. Same for a given district or precint.

tot_viviendas = 12171675.
IV4_censo.iloc[:, 1:].sum()/tot_viviendas

1 Membrana / cubierta asfáltica                0.179288
2 Baldosa / losa sin cubierta                  0.305800
3 Pizarra / teja                               0.095610
4 Chapa de metal sin cubierta                  0.361516
5 Chapa de fibrocemento / plástico             0.024129
6 Chapa de cartón                              0.008900
7 Caña / tabla / paja con barro / paja sola    0.014952
9 N/S. Depto en propiedad horizontal           0.009804
TOTAL                                          1.000000
dtype: float64

In [214]:
IV3_censo.iloc[:, 1:].sum()/tot_viviendas

1 Mosaico / baldosa / madera / cerámica / alfombra    0.765829
2 Cemento / ladrillo fijo                             0.202845
3 Ladrillo suelto / tierra                            0.025842
4 Otro                                                0.005484
TOTAL                                                 1.000000
dtype: float64

In [231]:
IV6_censo.iloc[:, 1:].sum()/tot_viviendas

1 Por cañeria dentro de la vivienda               0.885473
2 Fuera de la vivienda pero dentro del terreno    0.092493
3 Fuera del terreno                               0.022033
TOTAL                                             1.000000
dtype: float64

#### Prior probabilities (matrix entries) from survey info

In [333]:
qjkl = df.groupby(['IV4', 'IV3', 'IV6'])[['CODUSU']].nunique() # how many IDs with each combination
qjkl /= qjkl.sum()
qjkl = qjkl.unstack().unstack().fillna(0)

margins = []
for df in [IV4_censo, IV6_censo, IV3_censo]:
    margins += [(df.iloc[:, 1:-1].sum()/df.TOTAL.sum())]
    
a, b, c = tuple([m.values for m in margins])
df_ = pd.DataFrame(np.prod(np.ix_(a, b, c)).reshape(qjkl.values.shape), 
                  columns = qjkl.columns, index = qjkl.index)
uncorr_fill_p = df_

uncorr_fill_q = df_ * (qjkl == 0).astype(int)
qjkl = (1 - uncorr_fill_q.sum().sum())*qjkl + uncorr_fill_q

### Lagrangian function

In [427]:
# L(x0, q_mat, margins)

In [529]:
def L(x, q_mat, margins):
    shape = np.array(q_mat.shape)
    len_a = shape.sum()
    p_mat = np.array(x[:-len_a]).reshape(shape)
    a = np.array(x[-len_a:])
    
    if np.random.rand() < 0.0001:
        print p_mat
        print a

    MaxEnt = (p_mat*np.log(p_mat/q_mat))
    
    a_ix = np.insert(shape.cumsum(), [0], 0)
    
    lambda_terms = np.zeros(len(shape))
    for dim in range(len(shape)):
        lambda_terms[dim] = np.dot(a[a_ix[dim]:a_ix[dim + 1]], 
                                   margins[dim].values - p_mat.sum(axis = tuple([i for i in range(len(shape)) if i != dim])))

    return MaxEnt.sum() + lambda_terms.sum()

In [530]:
from scipy.optimize import minimize


shape = [len(m) for m in margins]
q_mat = qjkl.values.reshape(shape)

def pT(q_mat, margins):
    # This generates a left-stochastic matrix
    
#     p_0 = np.ones(np.array(q_mat.shape))/len(qjkl.values.flatten())
    p_0 = uncorr_fill_p.values.reshape(shape)
    a_ = np.ones(np.array(q_mat.shape).sum())
#     a_ = np.array([ 3.82209837, -0.67239368,0.9138076,1.71378012,1.70591917,1.34566778,
#  -0.10336548,1.71989107,2.7796474,-1.3430727,1.78366337,4.72804659,
#  -0.67614996,3.08805061,2.84402776])
    x0 = list(p_0.flatten()) + list(a_)

    res = minimize(lambda x: L(x, q_mat, margins), x0, 
                   method='Nelder-Mead',
                  options={'disp': True, 
                           'maxiter': 10000000, 
                           'xatol': 0.00001, 
                           'fatol': 0.00001, 
                           'maxfev': 1000000})
   
    return res

In [531]:
res = pT(q_mat, margins)

[[[  3.62609843e-01   6.02589766e-02   4.35852098e-03   7.94272906e-04]
  [  1.09170430e-02   3.00096500e-03   5.24251616e-04   2.03041187e-04]
  [  2.24758683e-03   1.03777406e-03   1.97424689e-05   9.37667599e-06]]

 [[  6.74923259e-01   7.42639059e-02   9.51198457e-03   1.42206110e-03]
  [  9.49027920e-03   4.76740941e-03   1.44992052e-04   5.72692500e-07]
  [  9.73164449e-04   1.73341688e-04   1.59880878e-06   2.54026269e-07]]

 [[  2.17662027e-01   7.53141469e-06   4.22879785e-03   9.27143727e-07]
  [  2.30187375e-03   2.19373304e-03   1.71137206e-04   5.18647128e-05]
  [  5.34145008e-04   2.03908873e-04   8.22343122e-05   8.80989190e-06]]

 [[  9.98846130e-01   1.05148053e-01   5.99252700e-03   2.94081169e-03]
  [  2.51544522e-02   2.72675630e-05   1.10147995e-03   3.45825041e-04]
  [  6.89421167e-03   1.04392367e-03   2.93306247e-04   5.38671624e-05]]

 [[  1.71913007e-02   4.16553025e-03   6.01819216e-05   5.22502455e-05]
  [  5.33702955e-04   2.50444734e-04   6.40096057e-05   

/home/miglesia/anaconda2/lib/python2.7/site-packages/IPython/kernel/__main__.py:11: RuntimeWarning: invalid value encountered in log


In [537]:
p_mat_ = np.array(res['x'][:-len_a]).reshape(shape)
a_ = np.array(res['x'][-len_a:])

In [538]:
p_= pd.DataFrame(p_mat_.reshape(qjkl.shape), 
             columns = qjkl.columns, index = qjkl.index)
p_ = p_/p_.sum().sum()
# p_.sum().sum()

2.8183442948302186

In [534]:
p_

CODUSU                                                                \
IV6         1                                               2                 
IV3         1         2         3             4             1             2   
IV4                                                                           
1    0.141882  0.015641  0.001328  2.952166e-04  2.900262e-03  1.369149e-03   
2    0.262956  0.032421  0.002498  2.435911e-04  1.394959e-03  1.051611e-03   
3    0.065675  0.000549  0.001293  3.456847e-06  6.175743e-07  9.337652e-04   
4    0.385724  0.041670  0.002848  1.346926e-03  6.949308e-03  3.386692e-09   
5    0.008833  0.001651  0.000043  1.973323e-05  4.050011e-04  1.286109e-04   
6    0.004151  0.000546  0.000015  3.406675e-08  7.559034e-06  1.126271e-09   
7    0.001333  0.000590  0.000001  2.572921e-05  1.244644e-03  8.299050e-05   
9    0.002423  0.000062  0.000093  5.341664e-06  1.821901e-04  2.266339e-05   

                                                                             
IV6                                 3                                        
IV3         3             4         1         2             3             4  
IV4                                                                          
1    0.000201  6.794651e-05  0.000841  0.000366  2.796933e-08  4.640061e-07  
2    0.000057  2.288506e-06  0.000751  0.000052  8.421282e-07  2.810720e-11  
3    0.000051  2.070349e-05  0.000081  0.000052  3.431275e-05  3.457732e-06  
4    0.000414  1.197275e-04  0.002830  0.000415  1.396692e-04  7.946080e-06  
5    0.000030  4.313255e-06  0.000238  0.000033  2.232306e-06  2.002925e-06  
6    0.000011  7.460832e-07  0.000114  0.000054  1.049171e-11  4.735263e-07  
7    0.000013  2.638256e-06  0.000045  0.000010  3.784740e-06  1.352610e-06  
9    0.000009  3.443087e-06  0.000071  0.000002  5.167761e-08  8.386387e-10

In [535]:
qjkl

CODUSU                                                              \
IV6         1                                       2                       
IV3         1         2         3         4         1         2         3   
IV4                                                                         
1    0.265412  0.012811  0.000811  0.000708  0.000855  0.001120  0.000059   
2    0.207639  0.021671  0.000295  0.000428  0.001459  0.002329  0.000133   
3    0.069758  0.002020  0.000074  0.000118  0.000074  0.000133  0.000229   
4    0.244096  0.054707  0.000737  0.000428  0.002742  0.010231  0.000899   
5    0.009862  0.002226  0.000059  0.000177  0.000221  0.000354  0.000177   
6    0.000516  0.000486  0.000088  0.000029  0.000029  0.000251  0.000206   
7    0.003096  0.002565  0.000177  0.000029  0.000118  0.000428  0.000324   
9    0.070363  0.000428  0.000015  0.000398  0.000339  0.000088  0.000023   

                                                       
IV6                   3                                
IV3         4         1         2         3         4  
IV4                                                    
1    0.000091  0.000044  0.000015  0.000102  0.000022  
2    0.000155  0.000059  0.000236  0.000015  0.000037  
3    0.000048  0.001613  0.000427  0.000054  0.000012  
4    0.000044  0.000310  0.000604  0.000103  0.000044  
5    0.000015  0.000015  0.000029  0.000029  0.000003  
6    0.000015  0.000150  0.000029  0.000044  0.000001  
7    0.000015  0.000252  0.000067  0.000029  0.000002  
9    0.000005  0.000165  0.000044  0.000006  0.000001

In [536]:
p_stacked = p_.stack().stack().reset_index()
print p_stacked.groupby('IV4')['CODUSU'].sum()
print p_stacked.groupby('IV3')['CODUSU'].sum()
print p_stacked.groupby('IV6')['CODUSU'].sum()

IV4
1    0.164892
2    0.301428
3    0.068698
4    0.442466
5    0.011390
6    0.004899
7    0.003354
9    0.002874
Name: CODUSU, dtype: float64
IV3
1    0.891033
2    0.097703
3    0.009087
4    0.002178
Name: CODUSU, dtype: float64
IV6
1    0.976167
2    0.017681
3    0.006152
Name: CODUSU, dtype: float64


In [527]:
margins

[1 Membrana / cubierta asfáltica                0.179288
 2 Baldosa / losa sin cubierta                  0.305800
 3 Pizarra / teja                               0.095610
 4 Chapa de metal sin cubierta                  0.361516
 5 Chapa de fibrocemento / plástico             0.024129
 6 Chapa de cartón                              0.008900
 7 Caña / tabla / paja con barro / paja sola    0.014952
 9 N/S. Depto en propiedad horizontal           0.009804
 dtype: float64, 1 Por cañeria dentro de la vivienda               0.885473
 2 Fuera de la vivienda pero dentro del terreno    0.092493
 3 Fuera del terreno                               0.022033
 dtype: float64, 1 Mosaico / baldosa / madera / cerámica / alfombra    0.765829
 2 Cemento / ladrillo fijo                             0.202845
 3 Ladrillo suelto / tierra                            0.025842
 4 Otro                                                0.005484
 dtype: float64]

In [528]:
q_stacked = qjkl.stack().stack()
print q_stacked.groupby('IV4')['CODUSU'].sum()
print q_stacked.groupby('IV3')['CODUSU'].sum()
print q_stacked.groupby('IV6')['CODUSU'].sum()

IV4
1    0.282050
2    0.234455
3    0.074560
4    0.314945
5    0.013167
6    0.001847
7    0.007102
9    0.071875
Name: CODUSU, dtype: float64
IV3
1    0.879189
2    0.113298
3    0.004689
4    0.002823
Name: CODUSU, dtype: float64
IV6
1    0.972226
2    0.023210
3    0.004565
Name: CODUSU, dtype: float64


In [11]:
## Model?
# It would be a max ent prolem minimizing distance between pjkl and priors qjkl, 
# using lagrange multipliers with the conditions that (hyper-) row and column sums match the margins.

In [12]:
# import scipy.maxentropy.conditionalmodel as cm

In [13]:
# def f_1(x):
#     return x

# F = [f_1]
# samplespace = np.ones((8, 4, 4))
# K = qjkl.values.reshape(8, 4, 4)
# cm(F, samplespace, K)